[package]
name = "python-skeleton"
version = "0.2.0"
edition = "2024"
description = "CLI to build a personalized python project for Data and ML"

[dependencies]
clap = { version = "4.5.54", features = ["cargo"] }
